---

#---------------------------------------------------
# Red Hat Subscription Management (RHSM)
# See https://access.redhat.com/
#---------------------------------------------------

- name: Force unregister before
  redhat_subscription:
   state: absent
  ignore_errors: true
  become: true

- name: Customer portal registration
  redhat_subscription:
   state: present
   username: "{{ rhsm_user_name }}"
   password: "{{ rhsm_user_pass }}"
   autosubscribe: false
  register: result
  until: result | succeeded
  retries: 10
  delay: 5
  become: true
  when: (rhsm_user_name is defined) and
        (rhsm_user_pass is defined)

- name: Activation key registration
  redhat_subscription:
    state: present
    activationkey: "{{ rhsm_key_id }}"
    org_id: "{{ rhsm_org_id }}"
    autosubscribe: false
  register: result
  until: result | succeeded
  retries: 10
  delay: 5
  become: true
  when: (rhsm_key_id is defined) and
        (rhsm_org_id is defined)

- name: Subscribe pool id
  shell: /usr/bin/subscription-manager attach --pool={{ rhsm_pool_id }}
  register: task_result
  until: task_result.rc == 0
  retries: 10
  delay: 5
  ignore_errors: no
  become: true
  when: rhsm_pool_id is defined

- name: Disable all rhsm repos
  shell: /usr/bin/subscription-manager repos --disable="*"
  retries: 5
  delay: 10
  become: true

- name: Disable all yum repos
  shell: /usr/bin/yum-config-manager --disable \*
  become: true

- name: Enable baseline repos
  shell: /usr/bin/subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms"
  retries: 5
  delay: 10
  become: true

- name: Upgrade packages
  yum: name=* state=latest
  become: true